# Generated by Django 4.2.25 on 2025-10-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameround',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='choices',
        ),
        migrations.AddField(
            model_name='game',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='correct_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.song'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='user_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game_api.song'),
        ),
    ]
